# Satz von Bayes und Hidden Markov Models
## 1. Satz von Bayes

Bob möchte gerne wissen, ob es regnet. Dazu schaut er aus dem Fenster, ob die Straße nass ist. Wenn es tatsächlich regnet, ist die Straße mit einer Wahrscheinlichkeit von 95 % nass (in 5 % der Fälle regnet es noch nicht lange genug, damit die Straße für Bob nass aussieht). Wenn es nicht regnet, ist die Straße mit einer Wahrscheinlichkeit von 25 % nass (weil der Nachbar von Bob den Rasensprenger laufen lässt, der auch die Straße trifft). Darüber hinaus weiß Bob, dass es an 40 % aller Tage regnet. Benutzen Sie für die folgenden Aufgaben die folgende Notation:

* $r$: Es regnet.
* $\bar{r}$: Es regnet nicht.
* $n$: Die Straße ist nass.

Berechnen Sie die folgenden Wahrscheinlichkeiten:
* $p(r) = 0,4$
* $p(\bar{r}) = 0,6$
* $p(n|r) = 0,95$
* $p(n|\bar{r}) = 0,25$
* $p(r|n) = \frac{p(n|r) \cdot f(r)}{p(n|r)\cdot p(r) + p(n| \bar{r}) \cdot p(\bar{r})}$ unten ist ein Normalisierungsterm, da Warhscheinlichkeit sich von oben zu eins aufaddieren muss $= \frac{0,95 \cdot 0,4}{0,95\cdot 0,4 + 0,25 \cdot 0,6} = 0,72$
* $p(s|o) = \frac{p(o|s) \cdot f(s)}{p(o)}$ wissen was die Namen sind: $\frac {likelihood\: \cdot\: prior}{evidence}$ 
* getz der Totalen Wahrscheinlihkeit: 

## 2. Hidden-Markov-Modelle

- wichtig
- ergebnisse vom Vortag auf das Neuere Ergebnis übertragen

Für eine Smartwatch soll ein System entwickelt werden, das automatisch erkennt, ob der
Träger gerade schläft. Die Smartwatch enthält einen Beschleunigungssensor, der entwe-
der den Wert wenig Bewegung“ oder den Wert viel Bewegung“ zurückliefert. Wenn der
Träger schläft, ist die Wahrscheinlichkeit für viel Bewegung“ 5 % und die Wahrscheinlichkeit für wenig Bewegung“ 95 %. Wenn der Träger wach ist, ist die Wahrscheinlichkeit
für viel Bewegung“ 60 % und die Wahrscheinlichkeit für wenig Bewegung“ 40 %. Wenn
der Träger schläft, ist die Wahrscheinlichkeit, dass er im nächsten Zeitschritt wach ist,
30 %. Wenn der Träger wach ist, ist die Wahrscheinlichkeit, dass er im nächsten Schritt
schläft, 20 %. Zu Anfang schläft der Träger mit einer Wahrscheinlichkeit von 50 %.

1. Spezifizieren Sie diesen Prozess als HMM, wobei der Zustand beschreibt, ob die Person schläft oder wach ist. Notieren Sie die Initialzustand und das Beobachtungsmodell.   

**Initialwahrscheinlichkeiten**
|S|W|
|---|---|
|$0,5$|$0,5$|
$=p(S_0)$


Welche Verteilung gibt uns das Trasitionsmodell an?

T=
| |S|W|
|---|---|---|
|**S**|0,7|0,2|
|**W**|0,3|0,8|

$=p(S_i\mid s_{i-1})$

-> Jede Spalte modelliert eine Warscheinlichkeitsverteilung
O =
| |S|W|
|---|---|---|
|**wB**|0,95|0,4|
|**vB**|0,05|0,6|

$=p(o_i\mid s_i)$

![visuelle Darstellung des Markhoff prozesses](image.png)

2. Berechnen Sie, ausgehend von der initialen Wahrscheinlichkeitsverteilung über den Zuständen, ...   
   a) die Vorhersage, d.h., Wahrscheinlichkeitsverteilung allein auf Basis des Transitionsmodelles!   
      1. $p(s_1) = \begin{array} {c c} p(s_1|s_0) * p(s_0) + \\ p(s_1|w_0) * p(w_0) \end{array}$
      2. $p(z_1) = T * s = \left(\begin{array}{c} 0,45 \\ 0,55\end{array}\right)$
      3. $p(Z_1\mid wB) = \frac{O_{[wB,]} * Z_1}{||O_{[wB,]}z_1||} = \left[\begin{array}{c} 0,66 \\ 0,34 \end{array}\right]$
      4. $p(s_1 | wB) = \frac{p(wB\mid s_1 * p(s_1))}{p(wB\mid s_1) * p(s_1) + p(wB\mid w_1)*p(w_1)}$ 

   b) die Korrektur nach der Beobachtung wenig Bewegung“!   


)

   b) die Korrektur nach der Beobachtung wenig Bewegung“!   


## 2. Implementierung

### Aufgabe 1 
Implementieren Sie zunächst für das oben beschriebene HMM das die Modelle für Transition und Observation, wie den Initalzustand des Systems! 

In [1]:
import numpy as np

In [2]:
#transition model
T = np.matrix([[0.8,0.2], [0.3,0.7]]).T
#prior
s0 = np.matrix([0.5,0.5]).T
#obs model
O = np.matrix([[0.6,0.4],[0.05,0.95]]).T
np.array(O[0,])

In [ ]:
array([[0.6, 0.05]])

### Aufgabe 2
Implementieren Sie eine Funktion `predict(s,T)` die als Parameter eine Prior-Verteilung $p(x_t | y_{1:t})$ als Vektor $s$ und das Transitionsmodell als Matrix `T` bekommt und als Ausgabe die Verteilung $p(x_{t+1} | y_{1:t})$ liefert.

In [3]:
def predict(s, T):
    return np.array(T * s)

### Aufgabe 3
Implementieren Sie eine Funktion `update(s,O,y)` die als Parameter eine Verteilung $p(x_{t+1} | y_{1:t})$ als Vektor $s$, ein Observationsmodell als Matrix `O` und eine Beobachtung $y_{t+1}$ als Integer `y` bekommt und als Ausgabe $p(x_{t+1} | y_{1:t+1})$ liefert.

In [4]:
def update(s, O, y):
    if y == "V":
        prow = 0
    else:
        orow = 1
    si = np.array(0[orow,]) * s.T
    return (si/np.sum(si)).T


### Aufgabe 4
Implementieren Sie eine Funktion `filter(s0,Y,T,O)` die als Parameter eine Prior-Verteilung $p(x_0)$ als Vektor `s0`, ein Transitions- und Beobachtungsmodell als Matrizen `T` und `O` und eine Sequenz von Beobachtungen $y_{1:T}$ als Vektor `yy` bekommt und für jedes $t = 1,...,T$ die Verteilung $p(x_t | y_{1:t})$ als Vektor berechnet und als Aufgabe somit eine $T \times 2$-Matrix liefert.

In [5]:
def filter(s0, O, T, yy):
    s = np.array(s0)
    ss = list([s])
    for y in yy:
            si = predict(s,T)
            s = update(si,0,y)
            ss.append(s)
    return ss




Testen Sie nun ihre Implementierung mit dem untenstehenden Code.

In [6]:
yy = ["W","W","V"]
ss = filter(s0,O,T,yy)
ss

[array([[0.5],
        [0.5]]),
 array([[0.33976834],
        [0.66023166]]),
 array([[0.2717807],
        [0.7282193]]),
 array([[0.90265233],
        [0.09734767]])]

# Mitnehmen

- satz von base
- markhoffhidden modelle
- einzelnen wahrscheinlichkeiten können wir auch so ausrechnen
